--- #YAML:1.0
name:               Win32-JobAdd
version:            1.00
abstract:           Add subprocesses to a "job" environment.
author:
    - BrowserUk <browseruk@cpan.org>, Dirk Joos <dirk@dirkundsari.de>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
